# Generated by Django 6.0.3 on 2026-04-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
        ('orgunits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='orgunits.orgunit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dept_head', 'Department Head'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
