# Generated by Django 6.0.5 on 2026-05-14 02:32

import decimal

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_ORG_TYPES = [
    ("College", "college", 10),
    ("Department", "department", 20),
    ("Office", "office", 30),
    ("Unit", "unit", 40),
]


def seed_default_org_types(apps, schema_editor):
    OrgType = apps.get_model("orgunits", "OrgType")
    for name, code, sort_order in DEFAULT_ORG_TYPES:
        OrgType.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "is_active": True,
                "sort_order": sort_order,
            },
        )


def remove_default_org_types(apps, schema_editor):
    OrgType = apps.get_model("orgunits", "OrgType")
    OrgType.objects.filter(code__in=[code for _, code, _ in DEFAULT_ORG_TYPES]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrgType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(blank=True, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "org_types",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RunPython(seed_default_org_types, remove_default_org_types),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("College", "College"),
                            ("Department", "Department"),
                            ("Office", "Office"),
                            ("Unit", "Unit"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("storage_quota_mb", models.PositiveIntegerField(default=1024)),
                (
                    "storage_used_mb",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_units",
                        to="orgunits.orgtype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="orgunits.orgunit",
                    ),
                ),
            ],
            options={
                "db_table": "org_units",
                "ordering": ["name"],
            },
        ),
    ]
