# Generated by Django 6.0.3 on 2026-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgunits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
