# Generated by Django 6.0.3 on 2026-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_base_path', models.CharField(default='/mnt/nas/documents', max_length=500)),
                ('max_file_size', models.PositiveIntegerField(default=20)),
                ('auto_archive', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
