/** Short label used when displaying employee numbers in lists and tables. */
export const EMPLOYEE_NUMBER_DISPLAY_LABEL = "Emp. No.";

/** Shown when a document requisitioner has no employee number. */
export const NO_EMPLOYEE_NUMBER_DISPLAY = "No Emp No. Provided";

export const EMPLOYEE_NUMBER_PLACEHOLDER = "Example: D-2122-GCM";
export const EMPLOYEE_NUMBER_HELPER_TEXT = "Format: Letter-Year-Code (dashes added automatically)";
export const REQUISITIONERS_DIRECTORY_TITLE = "Requisitioners Directory";

const INSTITUTIONAL_EMPLOYEE_NUMBER_PATTERN = /^[A-Z]-\d{4}-[A-Z0-9]+$/;
const LEGACY_NUMERIC_PATTERN = /^\d+$/;

/** Uppercase and trim while preserving hyphens for institutional format. */
export function sanitizeEmployeeNumberInput(value: string): string {
  return value.trim().toUpperCase();
}

/**
 * Formats employee number as user types: d2022dddd → D-2022-DDDD.
 * Partial input without year digits uses D-{suffix}, e.g. da → D-A.
 * Legacy numeric-only values are left unchanged.
 */
export function formatEmployeeNumberInput(value: string): string {
  const withoutSeparators = (value || "").replace(/[^A-Za-z0-9]/g, "");
  if (!withoutSeparators) {
    return "";
  }

  if (/^\d+$/.test(withoutSeparators)) {
    return withoutSeparators;
  }

  const alphanumeric = withoutSeparators.toUpperCase();
  const letterMatch = alphanumeric.match(/^[A-Z]/);
  if (!letterMatch) {
    return alphanumeric;
  }

  const letter = letterMatch[0];
  const rest = alphanumeric.slice(1);
  if (!rest) {
    return letter;
  }

  let year = "";
  let index = 0;
  while (index < rest.length && year.length < 4 && /\d/.test(rest[index])) {
    year += rest[index];
    index += 1;
  }

  const code = rest.slice(index);
  if (year) {
    if (!code) {
      return `${letter}-${year}`;
    }
    return `${letter}-${year}-${code}`;
  }

  return `${letter}-${rest}`;
}

function isLegacyNumericEmployeeNumber(value: string): boolean {
  return LEGACY_NUMERIC_PATTERN.test(value);
}

function validateInstitutionalEmployeeNumber(
  value: string,
  options: { required: boolean; allowLegacy: boolean }
): string | null {
  const trimmed = sanitizeEmployeeNumberInput(value);
  if (!trimmed) {
    return options.required ? "Employee number is required." : null;
  }
  if (INSTITUTIONAL_EMPLOYEE_NUMBER_PATTERN.test(trimmed)) {
    return null;
  }
  if (options.allowLegacy && isLegacyNumericEmployeeNumber(trimmed)) {
    return null;
  }
  return "Employee number must follow the format Letter-Year-Code (e.g. D-2122-GCM).";
}

/** Returns formatted display text, e.g. "Emp. No. D-2122-GCM", or null when empty. */
export function formatEmployeeNumberDisplay(value?: string | null): string | null {
  const trimmed = (value ?? "").trim();
  if (!trimmed) {
    return null;
  }
  return `${EMPLOYEE_NUMBER_DISPLAY_LABEL} ${trimmed}`;
}

function isLegacyAutoGeneratedEmployeeNumber(value: string): boolean {
  return value.toUpperCase().startsWith("AUTO-");
}

/** Requisitioner number for tables/cards — value only, or fallback when omitted. */
export function formatRequisitionerEmployeeNumberDisplay(value?: string | null): string {
  const trimmed = (value ?? "").trim();
  if (!trimmed || isLegacyAutoGeneratedEmployeeNumber(trimmed)) {
    return NO_EMPLOYEE_NUMBER_DISPLAY;
  }
  return trimmed;
}

/** Returns an error message when invalid, otherwise null. Empty values are allowed. */
export function validateOptionalEmployeeNumber(value: string): string | null {
  return validateInstitutionalEmployeeNumber(value, { required: false, allowLegacy: true });
}

/** Returns an error message when invalid, otherwise null. */
export function validateEmployeeNumber(value: string, allowLegacy = false): string | null {
  return validateInstitutionalEmployeeNumber(value, { required: true, allowLegacy });
}
